---
title: "App showing victims killed at Auschwitz concentration camp"
author: 
  - Sean Liu
thanks: "Code and data are available at: https://github.com/Sluuu/Essay12-Shiny, The interactive graph and an interactive table are available at:  https://gndr3e-yu0hsiang-liu.shinyapps.io/Essay12Shiny/"
date: today
date-format: long
abstract: "The interactive graph and the shiny app aims to analyze and visualize data on victims at Auschwitz concentration camp. Offering insights based on their birthplace, residence, or religion. The application allows users to interactively select specific criteria and view the corresponding data visualization and table."
format: pdf
number-sections: true
toc: true
bibliography: references.bib
---

\newpage
# Introduction
This Shiny app provides an interactive platform for analyzing and visualizing data related to the victims killed at Auschwitz concentration camp. It enables users to explore the dataset based on specific characteristics of the victims, such as their birthplace, residence, or religion. By offering a user-friendly interface, the app allows for dynamic selection and filtering, presenting the data through intuitive visualizations and detailed tables.

Upon selecting a category like birthplace, residence, or religion, users can further refine their analysis by choosing specific attributes within that category, such as the first letter of the birthplace or residence, or a particular religion. The app then generates a corresponding bar plot that displays the count of victims associated with the selected criteria, providing immediate visual insights into the dataset.

Additionally, the app includes a data table feature that shows detailed records filtered according to the user's selections. This table allows users to delve deeper into the data, offering a granular view of the individual entries that make up the visualized statistics.



# History of the Auschwitz concentration camp
In January 1945, Soviet troops liberated Auschwitz, ending the largest mass murder in a single location in human history. The camp, located in Poland, was evacuated by the Nazis just days before. The Holocaust Memorial Museum estimates that at least 960,000 Jews and thousands of others, including Poles, Roma, Soviet prisoners of war, and individuals from other nationalities, were systematically killed at Auschwitz. Grisly evidence of the horror was found by the Soviets, including thousands of starving prisoners, piles of clothing, human hair, and other belongings. Auschwitz consisted of three main camps, with Auschwitz II (Birkenau) being the largest and the site of the gas chambers. Medical experiments, including those by Dr Josef Mengele, were conducted at Auschwitz I. The camp was also a center for forced labor, with Auschwitz III (Monowitz) primarily serving as a labor camp for the German company IG Farben. As the Soviet army approached, the Nazis began evacuating the camp, resulting in the deaths of thousands of prisoners during forced marches. While many Nazi personnel served at Auschwitz, only a fraction have been prosecuted for their crimes, with ongoing efforts to bring remaining perpetrators to justice. [@HistoryofAuschwitz]

\newpage

# interactive graph and APP 

## Data 
The data was downloaded from the United States Holocaust Memorial Museum, the Holocaust Survivors and Victims Database included the victims' AUSCHWITZ DEATH CERTIFICATES from 1941-1943. The death certificates includes the victims' first and last name, date of birth, date of death, birthplaces, residences, and religions. Total of 65280 victims were recorded. 

## APP webpage 
From the user Interface, the drop-down menu shows the options for the data category Birthplace, Residence, and Religion. For the victims' birthplace and residence, the options are categorized by the first letter of its birthplace or residence instead of the whole name. As there weren't that many religions, for the victims' regions, the options are categorized by the full name of the regions. Depending on the user's selection, the app filters the data and generates a bar plot and a data table showcasing the count of victims based on the selected criteria.
Under the data table, there are a total of 7 categories

- Last Name: It shows the last name of the victim
- First Name(s): It shows the first name of the victim
- Date of Birth: It shows the date of birth of the victim, formatted as: YYYY-MM-DD
- Date of Death: It shows the date of death of the victim, formatted as: YYYY-MM-DD
- Birthplace: It shows the first letter of the birthplace of the victim
- Residence: It shows the first letter of the residence of the victim
- Religion: It shows the full name of the region of the victim

## Packages usage
The interactive graph and APP were constructed in R [@citeR] with the help of the following packages, `ggplot2` package of @ggplot2, `DT` package of @DT, `shiny` package of @shiny, `dplyr` package of @dplyr, `ggraph` package of @ggraph, and article `Welcome to the {tidyverse}` @rohan. 

\newpage

# Conclusion

In conclusion, this Shiny app represents a tool for engaging with the historical data surrounding the victims of the Auschwitz concentration camp. By leveraging an interactive platform, it not only aids in the visualization and analysis of the tragic events but also serves as an educational resource, emphasizing the scale and individuality of the loss experienced during the Holocaust.

The app allows users to navigate through a dataset derived from the Auschwitz death certificates, focusing on specific victim characteristics like birthplace, residence, and religion. The incorporation of a user-friendly interface enables both scholars and the general public to gain insights into the demographics of the victims, facilitating a deeper understanding of the diverse backgrounds of those who perished.

As we reflect on the history of Auschwitz, the liberation of the camp, and the ongoing efforts to prosecute those responsible, this app serves as a reminder of the critical need to remember and learn from the past. It underscores the importance of preserving the memory of the victims and reinforces our collective responsibility to prevent such atrocities in the future.




\newpage


# References


